query for login
moevm/nosql2h24-plants pull request #19
Opened 2024-11-06 22:50 UTC by defrozentruth

2024-11-06 23:01 UTC, LeraChernyakova requested changes

2024-11-06 23:01 UTC, LeraChernyakova commented on server/internal/storage/storage.go
> +	cursor, err := collection.Find(ctx, filter)
Тут лучше использовать FindOne, см. Получение CareRules

2024-11-07 10:26 UTC, AnjeZenda approved these changes

2024-11-07 16:02 UTC, AnjeZenda requested changes

2024-11-07 16:02 UTC, AnjeZenda commented on server/internal/storage/storage.go
> +	objid, err := primitive.ObjectIDFromHex(id)
objID или objId

2024-11-07 16:07 UTC, AnjeZenda commented on server/api/plantsapi/plants_api.proto
> +            get: "/api/trade/in{id}"
```suggestion
            get: "/api/trade/in/{id}"
```

2024-11-07 16:07 UTC, AnjeZenda commented on server/api/plantsapi/plants_api.proto
> +}
```suggestion
    message Plant{
         string name = 1;
    }
    message User{
        String name = 1;
        Plant plant = 2;
}
```

2024-11-07 16:08 UTC, AnjeZenda commented on server/internal/service/user_register_v1.go
> +	phone := ""
```suggestion
	var (
            email string
            phone string
)
```

2024-11-07 16:32 UTC, AnjeZenda commented on server/api/plantsapi/plants_api.proto
> +        Plant plant = 2;
```suggestion
        string name = 1;
        plant plant = 2;
```

2024-11-07 16:33 UTC, AnjeZenda commented on server/api/plantsapi/plants_api.proto
> +    Type Status = 3;
```suggestion
    int32 Status = 3;
```

2024-11-07 16:42 UTC, AnjeZenda commented on server/internal/service/get_trade_in_v1.go
> +	user, err := s.storage.GetTrade(ctx, req.id, 2)
```suggestion
	user, err := s.storage.GetTrade(ctx, req.Id, 2)
```

2024-11-07 16:51 UTC, AnjeZenda commented on server/internal/service/user_login_v1.go
> +		id: user,
```suggestion
		Id: user,
```

2024-11-07 16:53 UTC, AnjeZenda commented
\+ в storage.go не реализован метод GetTrade() а в Interface прокинут нужнго реализовать

2024-11-07 16:55 UTC, AnjeZenda commented on server/internal/service/get_trade_in_v1.go
> +	sb_ac.WriteString(trade.Offerer.FatherName)
поменяй модель

2024-11-07 18:03 UTC, defrozentruth commented on server/internal/service/get_trade_in_v1.go
> +			Plant: {Name: trade.Accepter.Plant.Name}},
у тебя у самого в модели через е написано

2024-11-07 19:45 UTC, LeraChernyakova commented on server/internal/service/get_trade_in_v1.go
> +	trade, err := s.storage.GetTrade(ctx, req.id, 2)
нужно писать req.Id

2024-11-07 19:46 UTC, LeraChernyakova commented on server/internal/service/get_trade_out_v1.go
> +	trade, err := s.storage.GetTrade(ctx, req.id, 1)
req.Id

2024-11-07 19:47 UTC, LeraChernyakova commented on server/internal/service/get_user_v1.go
> +	user, err := s.storage.GetUser(ctx, req.id)
req.Id

2024-11-07 20:26 UTC, merged